"""Add review_start_date to subtasks

Revision ID: 09bd225a7245
Revises: 20c1ec08906f
Create Date: 2026-03-23 22:55:31.088396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bd225a7245'
down_revision: Union[str, Sequence[str], None] = '20c1ec08906f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('review_start_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_subtasks_review_start_date'), 'subtasks', ['review_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtasks_review_start_date'), table_name='subtasks')
    op.drop_column('subtasks', 'review_start_date')
    # ### end Alembic commands ###
