"""Add workload_percent to subtasks

Revision ID: 20c1ec08906f
Revises: d6a131287aa3
Create Date: 2026-03-23 22:31:46.803432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c1ec08906f'
down_revision: Union[str, Sequence[str], None] = 'd6a131287aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('workload_percent', sa.Integer(), server_default='100', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtasks', 'workload_percent')
    # ### end Alembic commands ###
