"""make resumption_date optional

Revision ID: 2c6ce77ff281
Revises: 9247d6bc5b00
Create Date: 2026-05-01 23:41:26.412768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6ce77ff281'
down_revision: Union[str, Sequence[str], None] = '9247d6bc5b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtask_interruptions', 'resumption_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtask_interruptions', 'resumption_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
