"""add link_url to project task subtask

Revision ID: 2ea34e729429
Revises: 444b2352dcc6
Create Date: 2026-03-30 08:56:22.459851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea34e729429'
down_revision: Union[str, Sequence[str], None] = '444b2352dcc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('link_url', sa.String(length=500), nullable=True))
    op.add_column('subtasks', sa.Column('link_url', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('link_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'link_url')
    op.drop_column('subtasks', 'link_url')
    op.drop_column('projects', 'link_url')
    # ### end Alembic commands ###
