"""add work_days column

Revision ID: 444b2352dcc6
Revises: 3ce15756f9b1
Create Date: 2026-03-28 01:12:02.513139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444b2352dcc6'
down_revision: Union[str, Sequence[str], None] = '3ce15756f9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('work_days', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('subtasks', sa.Column('work_days', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('tasks', sa.Column('work_days', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'work_days')
    op.drop_column('subtasks', 'work_days')
    op.drop_column('projects', 'work_days')
    # ### end Alembic commands ###
