"""Initial Schema

Revision ID: 4675cbf7062a
Revises: 
Create Date: 2026-03-22 07:44:18.319475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4675cbf7062a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mst_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('holiday_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("holiday_name <> ''", name='check_holiday_name_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_holidays_holiday_date'), 'mst_holidays', ['holiday_date'], unique=True)
    op.create_index(op.f('ix_mst_holidays_id'), 'mst_holidays', ['id'], unique=False)
    op.create_table('mst_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("member_name <> ''", name='check_member_name_empty'),
    sa.CheckConstraint('sort_order >= 0', name='check_member_sort'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_members_id'), 'mst_members', ['id'], unique=False)
    op.create_table('mst_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.Column('color_code', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status_name <> ''", name='check_status_name_empty'),
    sa.CheckConstraint('sort_order >= 0', name='check_status_sort'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_statuses_id'), 'mst_statuses', ['id'], unique=False)
    op.create_table('mst_subtask_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type_name <> ''", name='check_type_name_empty'),
    sa.CheckConstraint('sort_order >= 0', name='check_type_name_sort'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mst_subtask_types_id'), 'mst_subtask_types', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('is_auto_planned_date', sa.Boolean(), nullable=False),
    sa.Column('is_auto_actual_date', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("project_name <> ''", name='check_project_name_empty'),
    sa.CheckConstraint('actual_start_date IS NULL OR actual_end_date IS NULL OR actual_end_date >= actual_start_date', name='check_project_actual_dates'),
    sa.CheckConstraint('planned_start_date IS NULL OR planned_end_date IS NULL OR planned_end_date >= planned_start_date', name='check_project_planned_dates'),
    sa.CheckConstraint('sort_order >= 0', name='check_project_sort'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('is_auto_planned_date', sa.Boolean(), nullable=False),
    sa.Column('is_auto_actual_date', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("task_name <> ''", name='check_task_name_empty'),
    sa.CheckConstraint('actual_start_date IS NULL OR actual_end_date IS NULL OR actual_end_date >= actual_start_date', name='check_task_actual_dates'),
    sa.CheckConstraint('planned_start_date IS NULL OR planned_end_date IS NULL OR planned_end_date >= planned_start_date', name='check_task_planned_dates'),
    sa.CheckConstraint('sort_order >= 0', name='check_task_sort'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('subtask_type_id', sa.Integer(), nullable=False),
    sa.Column('subtask_detail', sa.String(length=300), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('planned_effort_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('actual_effort_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('review_days', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_effort_days IS NULL OR actual_effort_days >= 0', name='check_subtask_actual_effort'),
    sa.CheckConstraint('actual_start_date IS NULL OR actual_end_date IS NULL OR actual_end_date >= actual_start_date', name='check_subtask_actual_dates'),
    sa.CheckConstraint('planned_effort_days IS NULL OR planned_effort_days >= 0', name='check_subtask_planned_effort'),
    sa.CheckConstraint('planned_start_date IS NULL OR planned_end_date IS NULL OR planned_end_date >= planned_start_date', name='check_subtask_planned_dates'),
    sa.CheckConstraint('progress_percent IS NULL OR (progress_percent BETWEEN 0 AND 100)', name='check_subtask_progress'),
    sa.CheckConstraint('review_days IS NULL OR review_days >= 0', name='check_subtask_review_days'),
    sa.CheckConstraint('sort_order >= 0', name='check_subtask_sort'),
    sa.CheckConstraint('ticket_id IS NULL OR ticket_id >= 0', name='check_subtask_ticket_id'),
    sa.ForeignKeyConstraint(['assignee_id'], ['mst_members.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['mst_statuses.id'], ),
    sa.ForeignKeyConstraint(['subtask_type_id'], ['mst_subtask_types.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtasks_actual_end_date'), 'subtasks', ['actual_end_date'], unique=False)
    op.create_index(op.f('ix_subtasks_actual_start_date'), 'subtasks', ['actual_start_date'], unique=False)
    op.create_index(op.f('ix_subtasks_assignee_id'), 'subtasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_subtasks_id'), 'subtasks', ['id'], unique=False)
    op.create_index(op.f('ix_subtasks_planned_end_date'), 'subtasks', ['planned_end_date'], unique=False)
    op.create_index(op.f('ix_subtasks_planned_start_date'), 'subtasks', ['planned_start_date'], unique=False)
    op.create_index(op.f('ix_subtasks_status_id'), 'subtasks', ['status_id'], unique=False)
    op.create_index(op.f('ix_subtasks_task_id'), 'subtasks', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtasks_task_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_status_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_planned_start_date'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_planned_end_date'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_assignee_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_actual_start_date'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_actual_end_date'), table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_mst_subtask_types_id'), table_name='mst_subtask_types')
    op.drop_table('mst_subtask_types')
    op.drop_index(op.f('ix_mst_statuses_id'), table_name='mst_statuses')
    op.drop_table('mst_statuses')
    op.drop_index(op.f('ix_mst_members_id'), table_name='mst_members')
    op.drop_table('mst_members')
    op.drop_index(op.f('ix_mst_holidays_id'), table_name='mst_holidays')
    op.drop_index(op.f('ix_mst_holidays_holiday_date'), table_name='mst_holidays')
    op.drop_table('mst_holidays')
    # ### end Alembic commands ###
