"""add subtask_interruptions table

Revision ID: 9247d6bc5b00
Revises: 2ea34e729429
Create Date: 2026-05-01 23:16:35.818614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9247d6bc5b00'
down_revision: Union[str, Sequence[str], None] = '2ea34e729429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtask_interruptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtask_id', sa.Integer(), nullable=False),
    sa.Column('interruption_date', sa.Date(), nullable=False),
    sa.Column('resumption_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('resumption_date >= interruption_date', name='check_interruption_dates'),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtask_interruptions_id'), 'subtask_interruptions', ['id'], unique=False)
    op.create_index(op.f('ix_subtask_interruptions_subtask_id'), 'subtask_interruptions', ['subtask_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtask_interruptions_subtask_id'), table_name='subtask_interruptions')
    op.drop_index(op.f('ix_subtask_interruptions_id'), table_name='subtask_interruptions')
    op.drop_table('subtask_interruptions')
    # ### end Alembic commands ###
