"""Add is_auto_effort to subtasks

Revision ID: d6a131287aa3
Revises: a8d5b96c4a02
Create Date: 2026-03-23 21:50:51.296136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a131287aa3'
down_revision: Union[str, Sequence[str], None] = 'a8d5b96c4a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_projects_assignee_id'), 'projects', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_projects_status_id'), 'projects', ['status_id'], unique=False)
    # Add column as nullable first
    op.add_column('subtasks', sa.Column('is_auto_effort', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE subtasks SET is_auto_effort = true")
    # Now set to NOT NULL
    op.alter_column('subtasks', 'is_auto_effort', nullable=False)
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_status_id'), 'tasks', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_column('subtasks', 'is_auto_effort')
    op.drop_index(op.f('ix_projects_status_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_assignee_id'), table_name='projects')
    # ### end Alembic commands ###
